### ISSUE TITLE
Redis example please

### ISSUE THREAD

**Issue by sshilko** [mallabee/queue#1]
Redis default connector is disabled, and it's unclear how to use it

registerDriver expects RedisConnector, which expects something with 
\Mallabee\Queue\Drivers\Redis\Factory
interface which doesnt exist

**Comment by dinbrca** [comment]
Hi,
I can see the problem.
I didn't have usage in Redis in my project so I haven't fully implemented it (can see at the "fix required" notes).
I will try to find time in this weekend to make sure it is a default driver.

If you are in a rush and have time to check laravel queues and implement it has in there it would be great until I'll reach it. 

Thanks for the heads up.

**Comment by sshilko** [comment]
He there, i ended up using illuminate/queue instead from dev-5.8 branch. They have fixed the blocking pop there (they say). The code there does NOT look good, and so the Symfony also is bad at handling Redis.

Just it might be tetter to remove the advertised Redis support from the readme as its confusing,
basicly i had the same issue (illuminate/queue had many dependencies) and was looking for solution
- symfony
- laravel
- ???

in the end after few days turned out all the framewors have non-ideal handling of redis queues :(

**Comment by dinbrca** [comment]
Yeah. the reason you noted "illuminate/queue had many dependencies" is exactly the reason why I created this. They are just trying to lock you up for using Laravel when there's no real need.
Once I will have time - I will try to add up Redis just as in illuminate/queue.
